
-- Dropping tables before creating new
DROP TABLE IF EXISTS teachers	CASCADE;
DROP TABLE IF EXISTS classes	CASCADE;
DROP TABLE IF EXISTS students	CASCADE;
DROP TABLE IF EXISTS subjects	CASCADE;
DROP TABLE IF EXISTS lessons	CASCADE;
DROP TABLE IF EXISTS journal	CASCADE;


-- teachers table
CREATE TABLE teachers (
	teacher_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	teacher_name	varchar(128)		NOT NULL,
	pass_hash		varchar(64)		NOT NULL
);

ALTER TABLE teachers
	ADD CONSTRAINT pk_teachers PRIMARY KEY (teacher_id);


-- classes table
CREATE TABLE classes (
	class_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	class_name		varchar(128)		NOT NULL
);

ALTER TABLE classes 
	ADD CONSTRAINT pk_classes PRIMARY KEY (class_id);


-- students table
CREATE TABLE students (
	student_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	class_id		integer				NOT NULL,
	student_name	varchar(128)		NOT NULL,
	skips			integer				DEFAULT(0) NOT NULL
);

ALTER TABLE students
	ADD CONSTRAINT pk_students PRIMARY KEY (student_id),
	ADD CONSTRAINT fk_students_classes FOREIGN KEY (class_id) REFERENCES classes;


-- subjects_table
CREATE TABLE subjects (
	subject_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	subject_name	varchar(128)		NOT NULL,
	teacher_id		integer				NOT NULL,
	class_id		integer				NOT NULL,
	hours			decimal				DEFAULT(0) NOT NULL
);

ALTER TABLE subjects
	ADD CONSTRAINT pk_subjects PRIMARY KEY (subject_id),
	ADD CONSTRAINT fk_subjects_teachers FOREIGN KEY (teacher_id) REFERENCES teachers,
	ADD CONSTRAINT fk_subjects_classes FOREIGN KEY (class_id) REFERENCES classes;
	

-- lessons table
CREATE TABLE lessons (
	lesson_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	subject_id		integer				NOT NULL,
	lesson_date		date				DEFAULT(CURRENT_DATE) NOT NULL,
	theme			varchar(1024)
);

ALTER TABLE lessons
	ADD CONSTRAINT pk_lessons PRIMARY KEY (lesson_id),
	ADD CONSTRAINT fk_lessons_subjects FOREIGN KEY (subject_id) REFERENCES subjects;
	

-- journal table
CREATE TABLE journal (
	record_id		integer				GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	lesson_id		integer				NOT NULL,
	student_id		integer				NOT NULL,
	mark			integer				DEFAULT (0) NOT NULL
	-- mark == 0 -> skip; mark > 0 && mark <= 10 -> default mark; mark > 10 && mark <= 20 -> exam mark; mark == 21 -> laboratory work
);

ALTER TABLE journal
	ADD CONSTRAINT pk_journal PRIMARY KEY (record_id),
	ADD CONSTRAINT fk_journal_lessons FOREIGN KEY (lesson_id) REFERENCES lessons,
	ADD CONSTRAINT fk_journal_students FOREIGN KEY (student_id) REFERENCES students;


INSERT INTO teachers (teacher_name, pass_hash)
VALUES 
	('Kostya Zinoviy Tchaikovsky', '6B86B273FF34FCE19D6B804EFF5A3F5747ADA4EAA22F1D49C01E52DDB7875B4B'),
	('Konstantin Avrora Antonov', 'D4735E3A265E16EEE03F59718B9B5D03019C07D8B6C51F90DA3A666EEC13AB35'),
	('Yuriy Germogen Lenin', '4E07408562BEDB8B60CE05C1DECFE3AD16B72230967DE01F640B7E4729B49FCE'),
	('Pasha Nil Maksimov', '4B227777D4DD1FC61C6F884F48641D02B4D121D3FD328CB08B5531FCACDABF8A'),
	('Nestor Grisha Pavlovsky', 'EF2D127DE37B942BAAD06145E54B0C619A1F22327B2EBBCFBEC78F5564AFE39D'),
	('Prokhor Maks Vinogradov', 'E7F6C011776E8DB7CD330B54174FD76F7D0216B612387A5FFCFB81E6F0919683');
	
INSERT INTO classes (class_name)
VALUES
	('105'),
	('205'),
	('305'),
	('405'),
	('209'),
	('309'),
	('409');
	
INSERT INTO subjects (subject_name, teacher_id, class_id, hours)
VALUES
	('Math pt. 1', 1, 1, 120),
	('Physics', 2, 5, 90),
	('Algorithmization', 1, 1, 80),
	('Math pt. 2', 1, 2, 120),
	('Computer security', 3, 3, 160),
	('Testing & debugging', 3, 3, 80),
	('Algorithmization', 1, 5, 80),
	('Graphics', 4, 6, 60),
	('Probability theory', 5, 6, 120),
	('Math pt. 2', 1, 5, 80);
	
INSERT INTO students (class_id, student_name)
VALUES 
	(1, 'Denis Vladlen Mikhailov'),
	(1, 'Savva Artur Alekseev'),
	(1, 'Feofan Borislava Aleksandrov'),
	(1, 'Miron Artyom Vasilev'),
	(1, 'Tamila Aleksandr Vasilyev'),
	(1, 'Varlam Valeriya Orlov'),
	(1, 'Arkhip Miroslava Konstantinov'),
	(1, 'Vissarion Grusha Romanov'),
	(1, 'Uliana Zinoviy Matveev'),
	(1, 'Tamara Zlata Viktorov'),
	(1, 'Vadim Ofeliya Tchaikovsky'),
	(1, 'Raisa Karp Andreev'),
	(2, 'Leontiy Galya Antonov'),
	(2, 'Ignatiy Tatiana Maksimov'),
	(2, 'Valeriya Pafnutiy Smirnov'),
	(2, 'Artur Nikita Voronin'),
	(2, 'Vilen Yuliy Kovalev'),
	(2, 'Matvei Adam Kovalyov'),
	(2, 'Ilia Vlad Popov'),
	(2, 'Ninel Iona Filippov'),
	(2, 'Eduard Aleksey Lenin'),
	(2, 'Amaliya Arkadi Medved'),
	(2, 'Vassily Katenka Vasilev'),
	(2, 'Yulianna Danila Sokolov'),
	(3, 'Benedikt Zoya Ignatiev'),
	(3, 'Mechislav Fedora Lagunov'),
	(3, 'Milana Vladlen Aleksandrov'),
	(3, 'Avrora Andrey Shwetz'),
	(3, 'Klava Sasha Krupin'),
	(3, 'Nastia Max Smirnov'),
	(3, 'Vitalik Vasya Krupin'),
	(3, 'Klava Alyonka Borisov'),
	(3, 'Nikandr Nikodim Tchaikovsky'),
	(3, 'Roma Savely Volkov'),
	(3, 'Roksolana Boleslava Bogomolov'),
	(3, 'Ekaterina Sabina Petrov'),
	(4, 'Dorofey Annushka Medved'),
	(4, 'Yefim Yudif Pavlov'),
	(4, 'Roman Raisa Mikhailov'),
	(4, 'Marina Dunya Matveev'),
	(4, 'Platon Ania Sokolov'),
	(4, 'Denis Yemelyan Alekseev'),
	(4, 'Sashok Mstislav Vasilev'),
	(4, 'Milana Zhenya Vasilev'),
	(4, 'Susanna Feliks Novikov'),
	(4, 'Feliks Apollinariya Volkov'),
	(4, 'Kazimir Fyodor Filippov'),
	(4, 'Andrei Anfisa Andreev'),
	(5, 'Viktoriya Matryona Bogomolov'),
	(5, 'Gleb Roman Shwetz'),
	(5, 'Demid Alyosha Matveev'),
	(5, 'Misha Vasilisa Sobol'),
	(5, 'Pavel Nikon Ivanov'),
	(5, 'Dmitriy Aksinia Vasilev'),
	(5, 'Vladislava Lilia Lagunov'),
	(5, 'Fyokla Sofron Lenin'),
	(5, 'Katerina Snezhana Sokolovsky'),
	(5, 'Alik Rolan Zima'),
	(5, 'Vyacheslav Ruvim Fyodorov'),
	(5, 'Yevdokim Leontiy Bogomolov'),
	(6, 'Ioann Anzhelika Filippov'),
	(6, 'Yevgeny Maria Krupin'),
	(6, 'Marina Katerina Smirnov'),
	(6, 'Ania Yana Rasputin'),
	(6, 'Sofia Vasily Kuznetsov'),
	(6, 'Timur Varfolomei Bogomolov'),
	(6, 'Yulian Vitali Krupin'),
	(6, 'Lavrenti Sasha Utkin'),
	(6, 'Arkady Avgusta Kovalev'),
	(6, 'Rudolf Varfolomey Orlov'),
	(6, 'Rozaliya Elvira Ivanov'),
	(6, 'Nina Liubov Smirnov'),
	(7, 'Liudmila Assol Kuznetsov'),
	(7, 'Galya Yermolai Medved'),
	(7, 'Matrona Arkadiy Lebedev'),
	(7, ' Alesya Maksim Novikov'),
	(7, 'Nika Galina Lenin'),
	(7, 'Yemelyan Galina Borisov'),
	(7, 'Sveta Grusha Nikolaev'),
	(7, 'Anatoliy Lyudmila Volkov '),
	(7, 'Evelina Innokentiy Lenin'),
	(7, 'Maks Nikolay Fedorov'),
	(7, 'Inna Ariadna Kovalchuk'),
	(7, 'Prokopiy Vladlen Viktorov');
	
INSERT INTO lessons (subject_id, lesson_date, theme)
VALUES 
	(1, '2021-09-01', 'Algebra - Fun with Calendars'),
	(1, '2021-09-02', 'Balancing Equations to Solve Variables'),
	(1, '2021-09-03', 'Egyptian Multiplication'),
	(1, '2021-09-04', 'Order of Operations'),
	(1, '2021-09-05', 'Solving for X'),
	(1, '2021-09-06', 'Using Equations to Solve Puzzles'),
	(1, '2021-09-07', 'Checking Up on Math: Checkbooks'),
	(1, '2021-09-08', 'Problem Solving Videos'),
	(1, '2021-09-09', 'Adventures in Statistics'),
	(1, '2021-09-10', 'Estimation Station'),
	(2, '2021-09-01', 'The Study of Kinetic Energy and Sports Science.'),
	(2, '2021-09-02', 'The Study of Human Energy Consumption and Nuclear Physics. '),
	(2, '2021-09-03', 'A Study on the Role of Physics in the Reduction of Global Warming '),
	(2, '2021-09-04', 'Making an Atomic Bomb: An exhaustive Study on the Principles by which an atomic bomb acts.'),
	(2, '2021-09-05', 'How Physics has evolved over the years and why it is essential in society.'),
	(2, '2021-09-06', 'The Roles physics plays in the health care industry.'),
	(2, '2021-09-07', 'Timeline of 20th-century innovation that revolutionized physics.'),
	(2, '2021-09-08', 'Other possible applications of the concept of magnetism.'),
	(2, '2021-09-09', 'Contributions of the Curies to nuclear physics?'),
	(2, '2021-09-10', 'Roles of Isaac Newton in the field of Physics as a Science.');
	
INSERT INTO journal	(lesson_id, student_id, mark)
VALUES 
	(1, 1 , 9 ),
	(1, 2 , 9 ),
	(1, 3 , 9 ),
	(2, 6 , 18),
	(2, 7 , 18),
	(2, 8 , 18),
	(2, 9 , 18),
	(3, 10, 0 ),
	(3, 11, 21),
	(3, 12, 21),
	(11, 49, 8 ),
	(11, 51, 8 ),
	(11, 52, 8 ),
	(13, 53, 3 ),
	(13, 54, 3 ),
	(13, 55, 3 ),
	(15, 56, 21),
	(15, 57, 21),
	(15, 58, 21);
	
DROP FUNCTION IF EXISTS get_classes, get_subjects;


-- get class info for left menu
CREATE FUNCTION get_classes (_teacher_id integer)
RETURNS TABLE (
	class_id	integer,
	class_name	VARCHAR
)
AS $$
BEGIN
	RETURN QUERY
	SELECT classes.class_id, classes.class_name 
	FROM classes
	WHERE classes.class_id IN (	SELECT subjects.class_id
					   			FROM subjects
					   			WHERE subjects.teacher_id = _teacher_id
							  );
END;
$$ LANGUAGE 'plpgsql';


-- get subject info for left menu
CREATE FUNCTION get_subjects (_class_id integer)
RETURNS TABLE (
	subject_id		integer,
	subject_name	VARCHAR
)
AS $$
BEGIN
	RETURN QUERY
	SELECT subjects.subject_id, subjects.subject_name
	FROM subjects 
	WHERE subjects.class_id = _class_id;
END;
$$ LANGUAGE 'plpgsql';

DROP FUNCTION IF EXISTS get_teachers, pass_valid;


-- get teacher names for logging in
CREATE FUNCTION get_teachers ()
RETURNS TABLE (
	teacher_id		integer,
	teacher_name	VARCHAR
)
AS $$
BEGIN
	RETURN QUERY 
	SELECT teachers.teacher_id, teachers.teacher_name
	FROM teachers
	ORDER BY teacher_name;
END;
$$ LANGUAGE 'plpgsql';


-- check if password hash valid
CREATE FUNCTION pass_valid(_teacher_id integer, hash varchar(64))
RETURNS integer
AS $$
DECLARE
	_hash varchar(64);
BEGIN
	_hash = upper((SELECT teachers.pass_hash FROM teachers WHERE teacher_id = _teacher_id));
	if _hash = hash then
		RETURN 1;
	else 
		RETURN 0;
	end if;
END;
$$ LANGUAGE 'plpgsql';

DROP FUNCTION IF EXISTS get_dates, get_students, get_marks;


-- get dates for grid headers
CREATE FUNCTION get_dates(_subject_id integer)
RETURNS TABLE (
	lesson_id	integer,
	lesson_date date
)
AS $$
BEGIN
	RETURN QUERY
	SELECT lessons.lesson_id, lessons.lesson_date
	FROM lessons
	WHERE lessons.subject_id = _subject_id
	ORDER BY lessons.lesson_date;
END;
$$ LANGUAGE 'plpgsql';

-- get sudent names for grid headers
CREATE FUNCTION get_students (_subject_id integer)
RETURNS TABLE (
	student_id		integer,
	student_name	VARCHAR
)
AS $$
BEGIN
	RETURN QUERY
	SELECT students.student_id, students.student_name
	FROM students
	WHERE students.class_id = (SELECT subjects.class_id
							   FROM subjects
							   WHERE subject_id = _subject_id)
	ORDER BY students.student_name;
END;
$$ LANGUAGE 'plpgsql';

--	get marks for every student
CREATE FUNCTION get_marks (_student_id integer, _subject_id integer)
RETURNS TABLE (
	lesson_id	integer,
	mark		integer
)
AS $$
BEGIN
	RETURN QUERY
	SELECT journal.lesson_id, journal.mark
	FROM journal
	WHERE	journal.student_id = _student_id AND
			journal.lesson_id IN (	SELECT lessons.lesson_id
						  			FROM lessons
						  			WHERE lessons.subject_id = _subject_id);
END;
$$ LANGUAGE 'plpgsql';


